############################################
#                                          #
#  CFLIB - Flexible Configuration Library  #
#  (c) 1995-2009 Stefan Habermehl          #
#                                          #
#  makefile.targets for Builds             #
#                                          #
#  Targets included at end of all          #
#  Build Configurations                    #
#                                          #
#  GNU Make Build Environment              #
#  based on Eclipse IDE Toolchains         #
#                                          #
#  @copyright (c) 2008 Stefan Habermehl    #
#  @license GNU GPL v3+ (see LICENSE.txt)  #
#                                          #
############################################
#
# @version SVN: $Id$
#
############################################

#### Directories / Build Configurations

%$(DIRSEP).update:
	@echo "Updating Build Configuration $(dir $@)"
	@echo "coming from directory: $(CURDIR)"  
	@cd "$(dir $@)" && make -C . all
	@echo 'Finished updating directory: $(dir $@)'
	@echo ' '

#### Libraries

$(CFLIB_BUILDS):: %: $(CFLIB_ROOT_REL)$(DIRSEP)%$(DIRSEP).update

$(CFLIB_PREF)%$(CFLIB_EXT):
	@echo "Building target $(notdir $@) in Directory $(dir $@)"
	make $(dir $@).update  
	@echo 'Finished building target: $@'
	@echo ' '

#### Documentation

documentation: $(CFLIB_DOCU_BUILDS)

CFLIB_DOCU_HTML := $(foreach ext, html css gif png, html$(DIRSEP)*.$(ext))

%$(DIRSEP)cflib_html.tgz: %$(DIRSEP)html$(DIRSEP)cflib.html %$(DIRSEP)html$(DIRSEP)index.html $(foreach target, $(CFLIB_DOCU_HTML), $(CFLIB_ROOT)$(DIRSEP)$(CFLIB_DOCU_DIR)$(DIRSEP)$(target))
	@echo "Creating HTML documentation archive $(notdir $@)"
	@cd "$(dir $@)" && tar czf $(notdir $@) $(CFLIB_DOCU_HTML)
	@echo 'Finished building target: $@'
	@echo ' '

%$(DIRSEP)cflib.pdf: %$(DIRSEP)latex$(DIRSEP)refman.tex
	@echo "Creating PDF documentation file $(notdir $@)"
	@cd "$(dir $<)" && make -C . all && $(CP) refman.pdf $@
	@echo 'Finished building target: $@'
	@echo ' '

%$(DIRSEP)cflib.man: %$(DIRSEP)man$(DIRSEP)man3$(DIRSEP)cf.h.3
	@echo "Updating Unix manual page $(notdir $@)"
	$(CP) $< $@
	@echo ' '

%$(DIRSEP)cflib.chm: %$(DIRSEP)html$(DIRSEP)index.hhc
	@echo "Created Compiled HTML Help file $(notdir $@)"
	@echo ' '

%$(DIRSEP)html$(DIRSEP)index.hhc: $(CFLIB_ROOT_REL)$(DIRSEP)cflib.chm.doxyfile $(CFLIB_EXAMPLES_LIB_FILE)
	@echo "Creating HTML Help source file $(notdir $@)"
	@echo "Calling Doxygen with configuration from $(notdir $<)"
	cd $(CFLIB_ROOT) && doxygen $(notdir $<)
	@echo ' '

%$(DIRSEP)cf.h.3 %$(DIRSEP)refman.tex %$(DIRSEP)html$(DIRSEP)index.html: $(CFLIB_ROOT_REL)$(DIRSEP)cflib.doxyfile $(CFLIB_EXAMPLES_LIB_FILE)
	@echo "Calling Doxygen with configuration from $(notdir $<)"
	cd $(CFLIB_ROOT) && doxygen $(notdir $<)
	@echo ' '

%$(DIRSEP)html$(DIRSEP)cflib.html: $(CFLIB_ROOT_REL)$(DIRSEP)cflib.tagfile.doxyfile $(CFLIB_EXAMPLES_LIB_FILE)
	@echo "Calling Doxygen with configuration from $(notdir $<)"
	cd $(CFLIB_ROOT) && doxygen $(notdir $<)
	$(CP) "$(dir $@)index.html" "$(dir $@)index_user.html"
	@echo ' '

#### Initialization of the system dependent custom project settings file
#### makefile.project[.<setup>]

ifndef CFLIB_PROJECT_CUSTOM
$(CFLIB_MAKEPROJECT):
ifneq ($(CFLIB_ROOT_REL),.)
	cd $(CFLIB_ROOT_REL) && make $(CFLIB_MAKEPROJECT)
else
	@echo "Initializing Custom Project File $@"
	@echo "######" >> $@
	@echo "# CFLIB Custom Project File:" >> $@
	@echo "# Change these settings according to your setup!" >> $@
	@echo "# This file will be overwritten, if CFLIB_PROJECT_CUSTOM is not defined!" >> $@
	@echo "######" >> $@
	@echo "CFLIB_PROJECT_CUSTOM :=" $@ >> $@
	@echo "CFLIB_ROOT :=" $(PWD) >> $@
	@echo "CFLIB_PROJECT :=" $(CFLIB_PROJECT) >> $@
	@echo "CFLIB_ADD_BUILDS :=" $(CFLIB_ADD_BUILDS) >> $@
	@echo "CFLIB_PREF :=" $(CFLIB_PREF) >> $@
	@echo "CFLIB_EXT :=" $(CFLIB_EXT) >> $@
	@echo "CFLIB_SHARED_EXT :=" $(CFLIB_SHARED_EXT) >> $@
	@echo "CFLIB_DEFINES :=" $(CFLIB_DEFINES) >> $@
	@echo "CFLIB_UNDEFINES :=" $(CFLIB_UNDEFINES) >> $@
	@echo "EXE :=" $(EXE) >> $@
	@echo "DIRSEP :=" $(DIRSEP) >> $@
	@echo "CP :=" $(CP) >> $@
	@echo "RM :=" $(RM) >> $@
	@echo "GREP :=" $(GREP) >> $@
	@echo "SORT :=" $(SORT) >> $@
	@echo "SHELL =" $(SHELL) >> $@
	@echo ' '
endif
endif


#### Misc. Targets

rebuild: clean all

help: info_system info_usage .targetcheck.all

.update: all

.targetcheck.%:
	@echo "Target '$(patsubst .targetcheck.%,%,$@)' status  (0 = up to date, 1 = needs update, 2 = no rule):"
	-@make -i -k -s -q $(patsubst .targetcheck.%,%,$@); echo Target status = $$?

_info.mk:
	@make -p -C .$(DIRSEP) .targetcheck.all > $@

info: info_system info_buildconf info_project info_commands

info_usage:
	@echo '#### CFLIB Makefile Usage:'
	@echo
	@echo "- Library Build: <build>"
	@echo "  <build> must be defined through CFLIB_PROJECT and CFLIB_ADD_BUILDS"
	@echo "  Current builds: $(CFLIB_LIB_BUILDS)"
	@echo
	@echo "- Examples: $(CFLIB_EXAMPLES_DIR) $(CFLIB_EXAMPLES_EXEC_FILES)"
	@echo
	@echo "- Package Build (all builds and examples): package"
	@echo
	@echo "- Documentation: documentation"
	@echo "  Current makes: $(CFLIB_DOCU_TARGETS)"
	@echo
	@echo "- Information:"
	@echo "  Quick Check: help"
	@echo "  All detailed Information: info"
	@echo "  Various details: info_system info_buildconf info_project info_commands"
	@echo "  Check target status: .targetcheck.<target>"
	@echo
	@echo "- Cleanup: clean <build>_clean $(CFLIB_EXAMPLES_DIR)_clean"
	@echo "  Rebuild: rebuild"
	@echo ' '


info_system:
	@echo
	@echo '#### CFLIB Makefile Infos:'
	@echo
	@echo -n "## System: "
	@uname -a
	@echo
	@echo OS = "$(OS)", OSTYPE = "$(OSTYPE)"
	@echo SHELL = "$(SHELL)"
	@echo PWD = "$(PWD)"
	@echo CURDIR = $(CURDIR)
	@echo PATH = $(PATH)
	@echo RM = $(RM)
	@echo
	@echo '## Make:'
	@echo
	@echo MAKE_COMMAND = $(MAKE_COMMAND)
	@echo MAKE_VERSION = $(MAKE_VERSION)
	@echo MAKELEVEL = $(MAKELEVEL)
	@echo MAKECMDGOALS = $(MAKECMDGOALS)
	@echo MAKEFILES = $(MAKEFILES)
	@echo ' '
	
info_buildconf:
	@echo '## Eclipse Build System:'
	@echo
	@echo LIBS = $(LIBS)
	@echo OBJS = $(OBJS)
	@echo ARCHIVES = $(ARCHIVES)
	@echo USER_OBJS = $(USER_OBJS)
	@echo OBJ_SRCS = $(OBJ_SRCS)
	@echo ASM_SRCS = $(ASM_SRCS)
	@echo O_SRCS = $(O_SRCS)
	@echo C_SRCS = $(C_SRCS)
	@echo S_SRCS = $(S_SRCS)
	@echo C_DEPS = $(C_DEPS)
	@echo SUBDIRS = $(SUBDIRS)
	@echo
	
info_project: _info.mk
	@echo '## CFLIB variables:'
	@echo
	@$(GREP) "^CFLIB" $< | $(SORT)
	@echo DIRSEP = $(DIRSEP)
	@echo EXE = $(EXE)
	@echo

info_commands: _info.mk
	@echo '## Command Overview:'
	@echo
	@$(GREP) "#.*commands to execute.*from" -A3 -B5 $< | $(GREP) -v "^# *[FINMP0-9]" | $(GREP) -v '^[- ]*$$'
	@echo


.PHONY: all rebuild clean examples package documentation \
		help info info_system info_buildconf info_project info_commands

####################### end makefile.targets
