.TH "bug" 3 "Wed Feb 27 2013" "Version Patchlevel 21" "CFLIB - Flexible Configuration Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 
.IP "\fBGroup \fBerrors\fP \fP" 1c
There are still errors without entry in error stack 
.IP "\fBGlobal \fBIsATerminal\fP (FILE *fp)\fP" 1c
ANSI C doesn't have function isatty(), we always return TRUE
.PP

