.TH "bug" 3 "31 Jan 2009" "Version Patchlevel 20" "CFLIB - Flexible Configuration Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 
 
.IP "\fBGroup \fBerrors\fP \fP" 1c
There are still errors without entry in error stack
.PP
.PP
.PP
 
.IP "\fBGlobal \fBIsATerminal\fP \fP" 1c
ANSI C doesn't have function isatty(), we always return TRUE
.PP
.PP

