.TH "Flexible Configuration Library" 3 "Wed Feb 27 2013" "Version Patchlevel 21" "CFLIB - Flexible Configuration Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flexible Configuration Library \- 
.PP
CFLIB is a small, simple, flexible and portable ANSI C Library to be used as configuration interface for user programs\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCore Features\fP"
.br
.RI "\fIBasic CFLIB Setup\&. \fP"
.ti -1c
.RI "\fBReport Generation\fP"
.br
.RI "\fIProcess templates doing variable substitution and file inclusion\&. \fP"
.ti -1c
.RI "\fBGeneral Utilities\fP"
.br
.RI "\fIGeneral Utility Macros and Functions\&. \fP"
.ti -1c
.RI "\fBSpecial Options Mask\fP"
.br
.RI "\fIThe \fB'Special Options Mask'\fP is a Bitmask of type \fBCFFLAGTYP\fP in Configuration Entry Structure Member \fBCONFIG::flag\fP containing Type, Instruction and Information Flags for a Parameter\&. \fP"
.ti -1c
.RI "\fBError Handling\fP"
.br
.RI "\fIError Codes, Functions and Structures\&. \fP"
.ti -1c
.RI "\fBAdvanced Features\fP"
.br
.RI "\fIDebugging and Utility Functions\&. \fP"
.ti -1c
.RI "\fBInformation Retrieval\fP"
.br
.RI "\fIThese functions and macros read entries from an initialized CFLIB database\&. \fP"
.ti -1c
.RI "\fBSetting and Saving the Configuration\fP"
.br
.RI "\fISet/Update Parameter Values or Save a Configuration File\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
CFLIB is a small, simple, flexible and portable ANSI C Library to be used as configuration interface for user programs\&. 

CFLIB builds and maintains a compact database structure consisting of a list of parameters with their name, content and some additional information about each parameter\&.
.PP
CFLIB targets the basic needs of technical, scientific or other programmers who want to spend minimal time on coding input, output, variable parsing, report generation and the like but still have a simple to use, reliable, flexible and portable configuration interface for their programs\&.
.PP
\fBMain Features\fP
.RS 4

.RE
.PP
.IP "\(bu" 2
Commandline, environment and terminal input parsing
.IP "  \(bu" 4
Configuration files
.IP "  \(bu" 4
File search
.IP "  \(bu" 4
Template driven report generation
.IP "  \(bu" 4
Automatic time and date update
.PP

.PP
.PP
\fBAuthor:\fP
.RS 4
Stefan Habermehl 
.RE
.PP
\fBLicense:\fP
.RS 4
http://www.gnu.org/licenses GNU General Public License v3 or later
.RE
.PP
\fBProject Homepage:\fP
.RS 4

.RE
.PP
Detailed information, source code and maybe updates are available from the library homepage:
.PP
.IP "\(bu" 2
http://cflib.berlios.de
.PP
.PP
\fBLocal References:\fP
.RS 4

.RE
.PP
.IP "\(bu" 2
Include file: \fI\fBcf\&.h\fP\fP 
.IP "  \(bu" 4
Library file: \fIlibcf\&.a\fP 
.IP "  \(bu" 4
Documentation: \fBFlexible Configuration Library\fP 
.PP

.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CFLIB - Flexible Configuration Library from the source code\&.
