.TH "CONFERR" 3 "29 Jan 2009" "Version Patchlevel 20" "CFLIB - Flexible Configuration Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CONFERR \- Library Internal: Error List Item.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct _cfe * \fBnext\fP"
.br
.RI "\fINext Error Pointer. \fP"
.ti -1c
.RI "int \fBerrcode\fP"
.br
.RI "\fINumeric Error Code. \fP"
.ti -1c
.RI "char \fBerrstr\fP [CF_MAXERRSTR]"
.br
.RI "\fIError Message String of maximum length \fBCF_MAXERRSTR\fP. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Library Internal: Error List Item. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CFLIB - Flexible Configuration Library from the source code.
