.TH "CONFIG" 3 "29 Jan 2009" "Version Patchlevel 20" "CFLIB - Flexible Configuration Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CONFIG \- CFLIB Configuration Database Entry.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.RI "\fI\fBParameter Name\fP \fP"
.ti -1c
.RI "char * \fBinhalt\fP"
.br
.RI "\fIParameter Content, see \fBParameter Default Value\fP. \fP"
.ti -1c
.RI "char \fBoption\fP"
.br
.RI "\fI\fBCommandline Option for Parameter\fP \fP"
.ti -1c
.RI "\fBCFFLAGTYP\fP \fBflag\fP"
.br
.RI "\fI\fBSpecial Options Mask\fP \fP"
.in -1c
.SH "Detailed Description"
.PP 
CFLIB Configuration Database Entry. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CFLIB - Flexible Configuration Library from the source code.
