.TH "Report Generation" 3 "29 Jan 2009" "Version Patchlevel 20" "CFLIB - Flexible Configuration Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Report Generation \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCF_DEF_VARDELIM\fP   '$()'"
.br
.RI "\fIDefault variable delimiter for \fBcfform()\fP. \fP"
.ti -1c
.RI "#define \fBCF_MAXINC\fP   8"
.br
.RI "\fIMaximum number of nested includes for \fBcfform()\fP. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcfform\fP (char *file, char *outfile, char *vd, int mode)"
.br
.RI "\fIProcess a Template from file or \fCstdin\fP and write generated Report to File or \fCstdout\fP. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int cfform (char * file, char * outfile, char * vd, int mode)"
.PP
Process a Template from file or \fCstdin\fP and write generated Report to File or \fCstdout\fP. 
.PP
The Report Template contains \fBVariables\fP like '$(\fIident\fP)' or whatever you set in \fIvd\fP. \fIident\fP may refer to a:
.PP
.IP "\(bu" 2
Parameter Name like '$(\fIname\fP)' : Substitute variable by parameter's value (from DB)
.IP "\(bu" 2
Include File Path like '$(FILE:\fI/my/path/to/incfile\fP)' : Substitute variable by content of include file
.IP "\(bu" 2
File Path and Section Include like '$(FILE:\fIincfile#\fIsect\fP)'\fP : Include section from include file between [\fIsect\fP] and next [\fI\fP...]
.IP "\(bu" 2
Variable File Include like '$(FILE::\fIvarname\fP)' : Include file from location given in parameter \fIvarname\fP 
.PP
.PP
\fBSee also:\fP
.RS 4
\fBAdvanced Usage Example\fP
.RE
.PP
\fBTodo\fP
.RS 4
Make \fBcfform()\fP work with buffers instead of files
.RE
.PP
\fBParameters:\fP
.RS 4
\fIfile\fP Name of Template File, \fCNULL\fP for \fCstdin\fP 
.br
\fIoutfile\fP Name of Output File, \fCNULL\fP for \fCstdout\fP 
.br
\fIvd\fP Variable Delimiters: string containing the three variable delimiters in the first three chars: to have variables like '$(\fIname\fP)', let the string be '$()'. This is also the default, if \fIvd\fP is \fCNULL\fP or string length < 3
.br
\fImode\fP Mode Mask: 
.PD 0

.IP "\(bu" 2
\fC0\fP : Normal 
.IP "\(bu" 2
\fC1\fP : Query for unresolved variables, (try to) include them in database 
.IP "\(bu" 2
\fC2\fP : Unset \fBCF_NOSAVE\fP flag for parsed vars 
.IP "\(bu" 2
\fC4\fP : Outfile Write \fIappend\fP, else \fIwrite\fP 
.PP
.RE
.PP
\fBReturns:\fP
.RS 4
.PD 0
.IP "\(bu" 2
\fC0\fP : Configuration has been saved to file successfully 
.IP "\(bu" 2
\fC!=0\fP : An error occurred:
.IP "  \(bu" 4
\fBCFE_NCA\fP : No Configuration database Available. 
.IP "  \(bu" 4
\fBCFE_FNF\fP : File Not Found, read access error. 
.IP "  \(bu" 4
\fBCFE_WAE\fP : Write Access Error.  
.PP

.PP
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CFLIB - Flexible Configuration Library from the source code.
