.TH "todo" 3 "28 Jan 2009" "Version Patchlevel 20" "CFLIB - Flexible Configuration Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBGlobal \fBcfdinichk\fP \fP" 1c
Make \fBcfdinichk()\fP work as reliable, complete tool with much more testing and \fBSpecial Options Mask\fP validation!
.PP
.PP
.PP
 
.IP "\fBGlobal \fBcfform\fP \fP" 1c
Make \fBcfform()\fP work with buffers instead of files
.PP
.PP
.PP
 
.IP "\fBPage \fBGeneral Notes\fP \fP" 1c
Make proper Man Pages with function references etc. 
.PP
Make Doxygen Developer Documentation 
.PP
More Modularization! Still very similar code in various functions 
.PP

